// src/components/common/locations.ts
export interface StateOption {
  value: string;
  label: string;
}

export interface CityOption {
  value: string;
  label: string;
}

export const stateOptions: StateOption[] = [
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
  // Union Territories
  { value: "Andaman & Nicobar", label: "Andaman & Nicobar" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Dadra & Nagar Haveli and Daman & Diu", label: "Dadra & Nagar Haveli & Daman & Diu" },
  { value: "Delhi", label: "Delhi" },
  { value: "Jammu & Kashmir", label: "Jammu & Kashmir" },
  { value: "Ladakh", label: "Ladakh" },
  { value: "Lakshadweep", label: "Lakshadweep" },
  { value: "Puducherry", label: "Puducherry" },
];

export const cityByState: Record<string, CityOption[]> = {
  "Andhra Pradesh": [
    { value: "Visakhapatnam", label: "Visakhapatnam" },
    { value: "Vijayawada", label: "Vijayawada" },
    { value: "Guntur", label: "Guntur" },
    { value: "Tirupati", label: "Tirupati" },
    { value: "Nellore", label: "Nellore" },
    { value: "Kurnool", label: "Kurnool" },
  ],
  "Arunachal Pradesh": [
    { value: "Itanagar", label: "Itanagar" },
    { value: "Naharlagun", label: "Naharlagun" },
    { value: "Pasighat", label: "Pasighat" },
  ],
  Assam: [
    { value: "Guwahati", label: "Guwahati" },
    { value: "Dibrugarh", label: "Dibrugarh" },
    { value: "Jorhat", label: "Jorhat" },
    { value: "Silchar", label: "Silchar" },
    { value: "Tezpur", label: "Tezpur" },
  ],
  Bihar: [
    { value: "Patna", label: "Patna" },
    { value: "Gaya", label: "Gaya" },
    { value: "Bhagalpur", label: "Bhagalpur" },
    { value: "Muzaffarpur", label: "Muzaffarpur" },
    { value: "Darbhanga", label: "Darbhanga" },
  ],
  "Chhattisgarh": [
    { value: "Raipur", label: "Raipur" },
    { value: "Bilaspur", label: "Bilaspur" },
    { value: "Durg", label: "Durg" },
    { value: "Korba", label: "Korba" },
  ],
  Goa: [
    { value: "Panaji", label: "Panaji" },
    { value: "Margao", label: "Margao" },
    { value: "Vasco da Gama", label: "Vasco da Gama" },
  ],
  Gujarat: [
    { value: "Ahmedabad", label: "Ahmedabad" },
    { value: "Surat", label: "Surat" },
    { value: "Vadodara", label: "Vadodara" },
    { value: "Rajkot", label: "Rajkot" },
    { value: "Bhavnagar", label: "Bhavnagar" },
    { value: "Jamnagar", label: "Jamnagar" },
  ],
  Haryana: [
    { value: "Gurugram", label: "Gurugram" },
    { value: "Faridabad", label: "Faridabad" },
    { value: "Panipat", label: "Panipat" },
    { value: "Hisar", label: "Hisar" },
    { value: "Karnal", label: "Karnal" },
    { value: "Rohtak", label: "Rohtak" },
  ],
  "Himachal Pradesh": [
    { value: "Shimla", label: "Shimla" },
    { value: "Dharamshala", label: "Dharamshala" },
    { value: "Manali", label: "Manali" },
    { value: "Solan", label: "Solan" },
  ],
  Jharkhand: [
    { value: "Ranchi", label: "Ranchi" },
    { value: "Jamshedpur", label: "Jamshedpur" },
    { value: "Dhanbad", label: "Dhanbad" },
    { value: "Bokaro", label: "Bokaro" },
  ],
  Karnataka: [
    { value: "Bengaluru", label: "Bengaluru" },
    { value: "Mysuru", label: "Mysuru" },
    { value: "Mangalore", label: "Mangalore" },
    { value: "Hubli", label: "Hubli" },
    { value: "Belagavi", label: "Belagavi" },
    { value: "Davanagere", label: "Davanagere" },
  ],
  Kerala: [
    { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
    { value: "Kochi", label: "Kochi" },
    { value: "Kozhikode", label: "Kozhikode" },
    { value: "Thrissur", label: "Thrissur" },
    { value: "Kollam", label: "Kollam" },
  ],
  "Madhya Pradesh": [
    { value: "Bhopal", label: "Bhopal" },
    { value: "Indore", label: "Indore" },
    { value: "Gwalior", label: "Gwalior" },
    { value: "Jabalpur", label: "Jabalpur" },
    { value: "Ujjain", label: "Ujjain" },
    { value: "Satna", label: "Satna" },
  ],
  Maharashtra: [
    { value: "Mumbai", label: "Mumbai" },
    { value: "Pune", label: "Pune" },
    { value: "Nagpur", label: "Nagpur" },
    { value: "Nashik", label: "Nashik" },
    { value: "Aurangabad", label: "Aurangabad" },
    { value: "Solapur", label: "Solapur" },
    { value: "Thane", label: "Thane" },
  ],
  Manipur: [
    { value: "Imphal", label: "Imphal" },
    { value: "Churachandpur", label: "Churachandpur" },
  ],
  Meghalaya: [{ value: "Shillong", label: "Shillong" }],
  Mizoram: [{ value: "Aizawl", label: "Aizawl" }],
  Nagaland: [
    { value: "Kohima", label: "Kohima" },
    { value: "Dimapur", label: "Dimapur" },
  ],
  Odisha: [
    { value: "Bhubaneswar", label: "Bhubaneswar" },
    { value: "Cuttack", label: "Cuttack" },
    { value: "Rourkela", label: "Rourkela" },
    { value: "Sambalpur", label: "Sambalpur" },
  ],
  Punjab: [
    { value: "Chandigarh", label: "Chandigarh" },
    { value: "Amritsar", label: "Amritsar" },
    { value: "Ludhiana", label: "Ludhiana" },
    { value: "Jalandhar", label: "Jalandhar" },
    { value: "Patiala", label: "Patiala" },
    { value: "Bathinda", label: "Bathinda" },
  ],
  Rajasthan: [
    { value: "Jaipur", label: "Jaipur" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Jodhpur", label: "Jodhpur" },
    { value: "Kota", label: "Kota" },
    { value: "Ajmer", label: "Ajmer" },
    { value: "Bikaner", label: "Bikaner" },
  ],
  Sikkim: [{ value: "Gangtok", label: "Gangtok" }],
  "Tamil Nadu": [
    { value: "Chennai", label: "Chennai" },
    { value: "Coimbatore", label: "Coimbatore" },
    { value: "Madurai", label: "Madurai" },
    { value: "Salem", label: "Salem" },
    { value: "Tiruchirappalli", label: "Tiruchirappalli" },
    { value: "Tirunelveli", label: "Tirunelveli" },
  ],
  Telangana: [
    { value: "Hyderabad", label: "Hyderabad" },
    { value: "Warangal", label: "Warangal" },
    { value: "Karimnagar", label: "Karimnagar" },
    { value: "Nizamabad", label: "Nizamabad" },
  ],
  Tripura: [{ value: "Agartala", label: "Agartala" }],
  "Uttar Pradesh": [
    { value: "Lucknow", label: "Lucknow" },
    { value: "Noida", label: "Noida" },
    { value: "Kanpur", label: "Kanpur" },
    { value: "Varanasi", label: "Varanasi" },
    { value: "Agra", label: "Agra" },
    { value: "Meerut", label: "Meerut" },
    { value: "Ghaziabad", label: "Ghaziabad" },
    { value: "Prayagraj", label: "Prayagraj" },
    { value: "Aligarh", label: "Aligarh" },
    { value: "Gorakhpur", label: "Gorakhpur" },
    { value: "Mathura", label: "Mathura" },
  ],
  Uttarakhand: [
    { value: "Dehradun", label: "Dehradun" },
    { value: "Haridwar", label: "Haridwar" },
    { value: "Rishikesh", label: "Rishikesh" },
    { value: "Nainital", label: "Nainital" },
  ],
  "West Bengal": [
    { value: "Kolkata", label: "Kolkata" },
    { value: "Howrah", label: "Howrah" },
    { value: "Durgapur", label: "Durgapur" },
    { value: "Siliguri", label: "Siliguri" },
    { value: "Asansol", label: "Asansol" },
  ],
  "Andaman & Nicobar": [{ value: "Port Blair", label: "Port Blair" }],
  Chandigarh: [{ value: "Chandigarh", label: "Chandigarh" }],
  Delhi: [
    { value: "New Delhi", label: "New Delhi" },
    { value: "Delhi", label: "Delhi" },
  ],
  "Dadra & Nagar Haveli and Daman & Diu": [
    { value: "Daman", label: "Daman" },
    { value: "Silvassa", label: "Silvassa" },
  ],
  "Jammu & Kashmir": [
    { value: "Srinagar", label: "Srinagar" },
    { value: "Jammu", label: "Jammu" },
    { value: "Anantnag", label: "Anantnag" },
    { value: "Baramulla", label: "Baramulla" },
  ],
  Ladakh: [
    { value: "Leh", label: "Leh" },
    { value: "Kargil", label: "Kargil" },
  ],
  Lakshadweep: [{ value: "Kavaratti", label: "Kavaratti" }],
  Puducherry: [
    { value: "Puducherry", label: "Puducherry" },
    { value: "Karaikal", label: "Karaikal" },
    { value: "Mahe", label: "Mahe" },
    { value: "Yanam", label: "Yanam" },
  ],
};

